version: "3.5"
services:

  client:
    build:
      context: ./client
      target: production
    container_name: streamer-client
    env_file:
      - .env
    expose:
      - 80
    image: streamer/client:latest
    networks:
      - streamer

  client-development:
    build:
      context: ./client
      target: development
    command: yarn dev
    container_name: streamer-client-development
    env_file:
      - .env
    expose:
      - 3000
    image: streamer/client:development
    networks:
      - streamer

  gateway:
    build:
      context: ./gateway
      target: production
    container_name: streamer-gateway
    env_file:
      - .env
    expose:
      - 80
      - 1935
    image: streamer/gateway:latest
    networks:
      - streamer

  gateway-development:
    build:
      context: ./gateway
      target: development
    container_name: streamer-gateway-development
    env_file:
      - .env
    expose:
      - 80
      - 1935
    image: streamer/gateway:development
    networks:
      - streamer

  restreamer:
    build:
      context: ./restreamer
    container_name: streamer-restreamer
    env_file:
      - .env
    environment:
      - RS_SNAPSHOT_INTERVAL=0
    expose:
      - 1935
      - 8080
    image: streamer/restreamer:latest
    networks:
      - streamer

networks:
  streamer:
    driver: bridge
    name: streamer
