version: "3.5"
services:

  client-development:
    volumes:
      - ./client:/app
      - /app/node_modules

  gateway:
    ports:
      - ${WEB_PORT}:80
      - ${RTMP_PORT}:1935

  gateway-development:
    ports:
      - ${WEB_PORT}:80
      - ${RTMP_PORT}:1935

  restreamer:
    environment:
      - RS_PASSWORD=${RESTREAMER_PASSWORD}
      - RS_TOKEN=${RESTREAMER_TOKEN}
      - RS_USERNAME=${RESTREAMER_USERNAME}
    volumes:
      - ${RESTREAMER_DATA_PATH}:/restreamer/db
