version: "3.5"
services:

  streamer-client-dev:
    ports:
      - ${DEV_PORT}:3000
    volumes:
      - ./client/.babelrc:/app/.babelrc
      - ./client/.eslintrc:/app/.eslintrc
      - ./client/package.json:/app/package.json
      - ./client/public/favicon.ico:/app/public/favicon.ico
      - ./client/src:/app/src
      - ./client/webpack.config.js:/app/webpack.config.js
      - ./client/yarn.lock:/app/yarn.lock

  streamer-gateway:
    ports:
      - ${WEB_PORT}:80
      - ${RTMP_PORT}:1935

  restreamer:
    environment:
      - RS_PASSWORD=${RESTREAMER_PASSWORD}
      - RS_TOKEN=${RESTREAMER_TOKEN}
      - RS_USERNAME=${RESTREAMER_USERNAME}
    volumes:
      - ${RESTREAMER_DATA_PATH}:/restreamer/db
