version: "3.5"
services:

  client:
    build:
      context: ./client
      target: production
    container_name: odo-stream-client
    env_file:
      - .env
    expose:
      - 80
    image: nicholasodonnell/odo-stream-client:latest
    networks:
      - odo-stream

  client-development:
    build:
      context: ./client
      target: development
    command: yarn dev
    container_name: odo-stream-client-development
    env_file:
      - .env
    expose:
      - 3000
    image: nicholasodonnell/odo-stream-client:development
    networks:
      - odo-stream

  gateway:
    build:
      context: ./gateway
      target: production
    container_name: odo-stream-gateway
    env_file:
      - .env
    expose:
      - 80
      - 1935
    image: nicholasodonnell/odo-stream-gateway:latest
    networks:
      - odo-stream

  gateway-development:
    build:
      context: ./gateway
      target: development
    container_name: odo-stream-gateway-development
    env_file:
      - .env
    expose:
      - 80
      - 1935
    image: nicholasodonnell/odo-stream-gateway:development
    networks:
      - odo-stream

  restreamer:
    build:
      context: ./restreamer
    container_name: restreamer
    env_file:
      - .env
    environment:
      - RS_SNAPSHOT_INTERVAL=0
    expose:
      - 1935
      - 8080
    image: nicholasodonnell/restreamer:latest
    networks:
      - odo-stream

networks:
  odo-stream:
    driver: bridge
    name: odo-stream
