version: "3.5"
services:

  client:
    build:
      context: ./client
    container_name: client
    env_file:
      - .env
    expose:
      - 80
    image: streamer/client:latest
    networks:
      - streamer

  client-dev:
    build:
      context: ./client
      target: base
    command: yarn dev
    container_name: client-dev
    env_file:
      - .env
    expose:
      - 3000
    image: streamer/client-dev:latest
    networks:
      - streamer

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    env_file:
      - .env
    expose:
      - 80
      - 1935
    image: streamer/gateway:latest
    networks:
      - streamer

  restreamer:
    build:
      context: ./restreamer
    container_name: restreamer
    env_file:
      - .env
    expose:
      - 1935
      - 8080
    image: streamer/restreamer:latest
    networks:
      - streamer

networks:
  streamer:
    driver: bridge
    name: streamer
