version: "3.5"
services:

  streamer-client-dev:
    ports:
      - ${DEV_PORT:-3000}:3000
    volumes:
      - ./client/.babelrc:/app/.babelrc
      - ./client/.eslintrc:/app/.eslintrc
      - ./client/package.json:/app/package.json
      - ./client/public/favicon.ico:/app/public/favicon.ico
      - ./client/src:/app/src
      - ./client/webpack.config.js:/app/webpack.config.js
      - ./client/yarn.lock:/app/yarn.lock

  streamer-gateway:
    ports:
      - ${WEB_PORT:-8080}:80
      - ${RTMP_PORT:-1935}:1935

  restreamer:
    environment:
      - RS_INPUTSTREAM=rtmp://127.0.0.1/live/external.stream?token=${RESTREAMER_TOKEN:-secret}
      - RS_PASSWORD=${RESTREAMER_PASSWORD:-password}
      - RS_TOKEN=${RESTREAMER_TOKEN:-secret}
      - RS_USERNAME=${RESTREAMER_USERNAME:-username}
    volumes:
      - ${RESTREAMER_DATA_PATH:-./restreamer/data}:/restreamer/db
