version: "3.5"
services:

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    image: stream/gateway:latest
    networks:
      - stream
    ports:
      - ${WEB_PORT:-8080}:80
      - ${RTMP_PORT:-1935}:1935

  player:
    build:
      context: ./player
    container_name: player
    expose:
      - 80
    image: stream/player:latest
    networks:
      - stream

  restreamer:
    container_name: restreamer
    environment:
      - RS_INPUTSTREAM=rtmp://127.0.0.1/live/external.stream?token=${RESTREAMER_TOKEN:-secret}
      - RS_PASSWORD=${RESTREAMER_PASSWORD:-password}
      - RS_TOKEN=${RESTREAMER_TOKEN:-secret}
      - RS_USERNAME=${RESTREAMER_USERNAME:-username}
    expose:
      - 1935
      - 8080
    image: datarhei/restreamer:latest
    networks:
      - stream
    volumes:
      - ${RESTREAMER_DATA_PATH:-./restreamer}:/restreamer/db

networks:
  stream:
    driver: bridge
    name: stream
